name: Security Alerts

on:
    # セキュリティアラートが作成された時
    repository_vulnerability_alert:
        types: [create, resolve]
    # セキュリティアドバイザリが公開された時
    security_advisory:
        types: [published]
    # 手動実行も可能
    workflow_dispatch:

permissions:
    contents: write
    security-events: write
    pull-requests: write

jobs:
    security-scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: maven

            - name: Run security scan with Maven
              run: |
                  echo "セキュリティスキャンを実行中..."
                  mvn org.owasp:dependency-check-maven:check
                  echo "セキュリティスキャンが完了しました"

            - name: Upload security report
              uses: actions/upload-artifact@v4
              with:
                  name: security-report
                  path: target/dependency-check-report.html
                  retention-days: 30

            - name: Comment on security issues
              if: github.event_name == 'repository_vulnerability_alert'
              run: |
                  echo "セキュリティアラートが検出されました:"
                  echo "パッケージ: ${{ github.event.alert.affected_package_name }}"
                  echo "バージョン: ${{ github.event.alert.affected_package_version }}"
                  echo "深刻度: ${{ github.event.alert.severity }}"

                  # 必要に応じてSlackやメール通知を追加
                  # curl -X POST -H 'Content-type: application/json' \
                  #   --data '{"text":"セキュリティアラート: ${{ github.event.alert.affected_package_name }}"}' \
                  #   ${{ secrets.SLACK_WEBHOOK_URL }}
