name: Security Alerts

on:
    # スケジュール実行（毎日午前2時 UTC）
    schedule:
        - cron: "0 2 * * *"
    # 手動実行も可能
    workflow_dispatch:
    # プッシュ時に実行
    push:
        branches: [main, master]
    # プルリクエスト時に実行
    pull_request:
        branches: [main, master]

permissions:
    contents: write
    security-events: write
    pull-requests: write

jobs:
    security-scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: maven

            - name: Run security scan with Maven
              run: |
                  echo "セキュリティスキャンを実行中..."
                  mvn org.owasp:dependency-check-maven:check
                  echo "セキュリティスキャンが完了しました"

            - name: Upload security report
              uses: actions/upload-artifact@v4
              with:
                  name: security-report
                  path: target/dependency-check-report.html
                  retention-days: 30

            - name: Check for security vulnerabilities
              run: |
                  echo "セキュリティスキャンの結果を確認中..."

                  # セキュリティレポートの存在確認
                  if [ -f "target/dependency-check-report.html" ]; then
                      echo "セキュリティレポートが生成されました"

                      # 脆弱性の数をカウント（簡易的な方法）
                      VULNERABILITIES=$(grep -c "vulnerability" target/dependency-check-report.html || echo "0")
                      echo "検出された脆弱性数: $VULNERABILITIES"

                      if [ "$VULNERABILITIES" -gt 0 ]; then
                          echo "⚠️ セキュリティ脆弱性が検出されました"
                          echo "詳細はアーティファクトのセキュリティレポートを確認してください"
                      else
                          echo "✅ セキュリティ脆弱性は検出されませんでした"
                      fi
                  else
                      echo "⚠️ セキュリティレポートが生成されませんでした"
                  fi

            - name: Notify on security issues
              if: failure()
              run: |
                  echo "セキュリティスキャンで問題が発生しました"
                  echo "ログを確認し、必要に応じて手動で調査してください"

                  # 必要に応じてSlackやメール通知を追加
                  # if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
                  #   curl -X POST -H 'Content-type: application/json' \
                  #     --data '{"text":"セキュリティスキャンでエラーが発生しました"}' \
                  #     ${{ secrets.SLACK_WEBHOOK_URL }}
                  # fi
